apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-http-server-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/denisgdevops/ruby-http-server-app.git  # Replace with your GitLab repo URL
    targetRevision: HEAD
    path: plaform/helm # Path to your application's Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc  # Minikube Kubernetes API server
    namespace: default  # The target namespace in Minikube

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true  # Add any other syncPolicy settings as needed